name: rust

on:
  push:
    branches:
      - trunk

jobs:
  ci:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            features: ''

          - platform: 'windows-latest'
            features: '--features=anyhow'

          - platform: 'ubuntu-latest'
            features: ''

          - platform: 'ubuntu-latest'
            features: '--features=anyhow'

    runs-on: ${{ matrix.platform }}
    steps:
      - name: "Setup: Repo"
        uses: actions/checkout@v4

      - name: "Setup: Rust"
        uses: dtolnay/rust-toolchain@stable

      - name: "Rust: Build"
        run: cargo build --release ${{ matrix.features }}

      - name: "Rust: Test"
        run: cargo test ${{ matrix.features }}

      - name: "Rust: Test Docs"
        run: cargo test --doc ${{ matrix.features }}

      - name: "Rust: Clippy"
        run: cargo clippy ${{ matrix.features }} -- -D warnings

      - name: "Rust: Format"
        run: cargo fmt --check